name: Sync from Bitbucket to GitHub

on:
  # Trigger this workflow when there’s a push to the master branch on GitHub
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      - name: Add Bitbucket Remote and Pull Changes
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          git remote add bitbucket https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.rampgroup.com/scm/~krishna.badugu_rampgroup.com/test_repo.git
          git fetch bitbucket master
          git merge bitbucket/master --allow-unrelated-histories
          git push origin master
