name: Sync from Bitbucket to GitHub

on:
  # Trigger this workflow when there’s a push to the master branch on GitHub
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BITBUCKET_SSH_KEY1 }}

      - name: Add Bitbucket Remote and Pull Changes
        run: |
          git remote add bitbucket ssh://git@bitbucket.rampgroup.com:7999/~krishna.badugu_rampgroup.com/test_repo.git
          git fetch bitbucket master
          git merge bitbucket/master --allow-unrelated-histories
          git push origin master
